import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getBaseCurrencyValues, TTotalPrice } from '../services/currency';

const Home: NextPage<{ currency: TTotalPrice }, {}> = ({ currency }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>
                {/*<Cart></Cart>*/}
            </main>

            <footer className={styles.footer}>
                <div>Created by <b>Askar Musin</b>, 2021</div>
            </footer>
        </div>
    );
};

Home.getInitialProps = async () => {
    // const currency = await getBaseCurrencyValues();
    const currency = {
        dollars: 1,
        euros: 0.8489,
        pounds: 0.7246,
        yens: 110.0331,
        rubles: 72.6444,
    };
    return { currency };
};

export default Home;
