export const CURRENCY_NAME = {
	RUBLES: 'rubles',
	EUROS: 'euros',
	DOLLARS: 'dollars',
	POUNDS: 'pounds',
	YENS: 'yens',
};
export const CURRENCY_ID = {
	[CURRENCY_NAME.RUBLES]: 'RUB',
	[CURRENCY_NAME.EUROS]: 'EUR',
	[CURRENCY_NAME.DOLLARS]: 'USD',
	[CURRENCY_NAME.POUNDS]: 'GBP',
	[CURRENCY_NAME.YENS]: 'JPY',
};
export const CURRENCY_ID_NAME = {
	[CURRENCY_ID[CURRENCY_NAME.RUBLES]]: CURRENCY_NAME.RUBLES,
	[CURRENCY_ID[CURRENCY_NAME.EUROS]]: CURRENCY_NAME.EUROS,
	[CURRENCY_ID[CURRENCY_NAME.DOLLARS]]: CURRENCY_NAME.DOLLARS,
	[CURRENCY_ID[CURRENCY_NAME.POUNDS]]: CURRENCY_NAME.POUNDS,
	[CURRENCY_ID[CURRENCY_NAME.YENS]]: CURRENCY_NAME.YENS,
};
